### ISSUE TITLE
Releases for x86

### ISSUE THREAD

**Issue by hakimkhalafi** [FFMG/myoddweb.classifier#6]
Hey, would you be able to release the setup executables for 32bit?

**Comment by FFMG** [comment]
Hey, sorry I only saw this now, 
The setup should pick up what version you are running on.

Is that not the case for you?

**Comment by hakimkhalafi** [comment]
Running the installation .exe in a 32bit system gave a popup saying the program is 32bit incompatible

**Comment by FFMG** [comment]
Just to confirm, is that the same issue as that one ...

![image](https://user-images.githubusercontent.com/5659271/30518597-c389e8fe-9b82-11e7-9a8a-b21e1f7dd581.png)

(of course  I will fix that one, I just want to know if they are related)

**Comment by hakimkhalafi** [comment]
Yep that is exactly the one!

**Comment by FFMG** [comment]
Great, thanks for the help, this was fixed in the [latest release](https://github.com/FFMG/myoddweb.classifier/releases/latest).

Thanks again

F.
