### ISSUE TITLE
No Mail Notification

### ISSUE THREAD

**Issue by Swerner1975** [FFMG/myoddweb.classifier#7]
It's not a real issue, but if the mail is classified and than moved to the correct folder, the Outlook Mail Notifications doesn't open anymore. So you get no notification about new mails.

Maybe could help to delay the move of the mails or the addon himself triggers the notification?

Thanks for the addon, thumbs up. I've searched very long for an alternative of "popfile" and "outclass" (outclass works only correct until Outlook 2003) ...

**Comment by FFMG** [comment]
Thanks for the comments :), I have never used Outclass, but I am familiar with Popfile I used it many years ago until we moved to an exchange server and it wasn't an option anymore.

Regarding your issue, just to confirm, are you talking about the message pop-up or just the envelope notification on in the taskbar, (or both)?

Also, can you confirm what version of Windows+Outlook you are using.

I will setup a test rig and give it a try here.

**Comment by Swerner1975** [comment]
I use Outlook 2013 (Exchange Server) and Windows 10.
In Windows 10 the envelop notifications on the taskbar does'nt appears, but only if the addon moves the categorized mails in the folders. If the addon can't categorize the mail and the mail remains in the Inbox, the envelop notification appears.

I don't know, if the message pop-ups in Windows 7 also does not appear. I cannot test this...

Maybe the addon moves the mail too quickly to the folders.

**Comment by FFMG** [comment]
Ok, I will add a new option to delay the move to see if that helps.
I will add a comment here when done.

**Comment by FFMG** [comment]
I have made the change in the [develop branch](https://github.com/FFMG/myoddweb.classifier/tree/develop) (7.0.2), if you want, you can get it there, otherwise I will complete some of my tests and release at the end of the week,

**Comment by FFMG** [comment]
You can get the [pre-release here](https://github.com/FFMG/myoddweb.classifier/releases/tag/0.7.0.2).

Increase the option from 1seconds to maybe 4 or 5 seconds.

**Comment by Swerner1975** [comment]
Hi,

unfortunately, the delay does not work for me. I have set it to 30 seconds (for testing), but the mail is immediately classified and moved.

**Comment by FFMG** [comment]
Hum... ok, let me have another look

**Comment by FFMG** [comment]
Ok... there is an issue, I will fix it a do another release asap.

**Comment by FFMG** [comment]
Ok, I have a [new release](https://github.com/FFMG/myoddweb.classifier/releases/tag/0.7.0.4) that should take your delays into account.

In my tests, a delay of 0 will cause no alert/rules to fire, but a delay of 2 seconds or more does the trick.

**Comment by Swerner1975** [comment]
I am testing the new release currently and it looks good so far.
Sometimes it seems that the delay does not appear when I start Outlook, but I have not been able to emulate it. I'll keep watching this.

**Comment by FFMG** [comment]
Thanks for the feedback, 

> I am testing the new release currently and it looks good so far.

Interesting, I will look out for that as well as I have a test environment for that case.
