### ISSUE TITLE
On first Outlook start - Inbox mails are not moved

### ISSUE THREAD

**Issue by Swerner1975** [FFMG/myoddweb.classifier#8]
Hi,

I use Outlook 2013 with Exchange Server.

Use Case:

- shut down and end Outlook
- shut down Laptop in standby at the evening
- in the morning I start the Laptop and then I start Outlook
- Outlook shows me new mails in the Inbox
- the mails are classified, but after the delay (10s) the mails are not moved to the folders
- when I close Outlook and start it again
- the mails in the Inbox now moved in the folders after the delay
- all other new mails then also moved

Can you check if you can replicate this?

**Comment by FFMG** [comment]
Hi, I will have a look, I just need to set it up on my side.

**Comment by FFMG** [comment]
Sorry about the delay, I completely forgot about this for a while :(
I have managed to reproduce the issue you describe.

I will make a couple of changes and release something soon.

**Comment by Swerner1975** [comment]
Any news about this? :)

**Comment by FFMG** [comment]
Fixed in latest release

Added a "rescan" option
